services:
  oj-slave:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CPY_VER=3.13.2
        - PYPY_VER=3.11-v7.3.19
    environment:
      - CELERY_BROKER_URL=redis://redis-np:6379/0
      - CELERY_RESULT_BACKEND=redis://redis-np:6379/0
    command:
      [
        "poetry",
        "run",
        "uvicorn",
        "src.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
      ]
    ports:
      - 8000:8000
    networks:
      - oj-network
  redis-np:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - oj-network
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CPY_VER=3.13.2
        - PYPY_VER=3.11-v7.3.19
    healthcheck:
      test: ["CMD-SHELL", "python3 --version"]
      interval: 1s
      timeout: 1s
      retries: 3
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis-np:6379/0
      - CELERY_RESULT_BACKEND=redis://redis-np:6379/0
    depends_on:
      - redis-np
    networks:
      - oj-network
    entrypoint:
      [
        "poetry",
        "run",
        "celery",
        "--app=src.celery_app",
        "worker",
        "--loglevel=info",
        "--concurrency=2",
      ]
    deploy:
      replicas: 2
  # autoheal:
  #   restart: always
  #   image: willfarrell/autoheal
  #   container_name: autoheal
  #   environment:
  #     - AUTOHEAL_CONTAINER_LABEL=all
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
networks:
  networks:
  oj-network:
    driver: bridge
